var config = {
        options: {
            buildDir: '<%= settings.dist %>', // Where the build version of my node-webkit app is saved
            macIcns: '<%= settings.app %>/soundnode.icns',
            downloadUrl: 'http://www.soundnodeapp.com/build/',
            platforms: ['linux32', 'linux64', 'osx64', 'win32'],
            version: '0.12.3'
        },
        src: [
            '<%= settings.app %>/index.html',
            '<%= settings.app %>/package.json',
            '<%= settings.app %>/soundnode.icns',
            '<%= settings.app %>/soundnode.png',
            '<%= settings.app %>/views/**/*',
            '<%= settings.app %>/public/js/**/*',
            '<%= settings.app %>/public/img/**/*',
            '<%= settings.app %>/public/stylesheets/css/**/*',
            '<%= settings.app %>/dist/**/*',
            './node_modules/ansi-regex/**/*',
            './node_modules/ansi-styles/**/*',
            './node_modules/asn1/**/*',
            './node_modules/assert-plus/**/*',
            './node_modules/async/**/*',
            './node_modules/aws-sign2/**/*',
            './node_modules/aws4/**/*',
            './node_modules/bl/**/*',
            './node_modules/boom/**/*',
            './node_modules/caseless/**/*',
            './node_modules/chalk/**/*',
            './node_modules/combined-stream/**/*',
            './node_modules/commander/**/*',
            './node_modules/core-util-is/**/*',
            './node_modules/cryptiles/**/*',
            './node_modules/dashdash/**/*',
            './node_modules/delayed-stream/**/*',
            './node_modules/ecc-jsbn/**/*',
            './node_modules/escape-string-regexp/**/*',
            './node_modules/extend/**/*',
            './node_modules/extsprintf/**/*',
            './node_modules/forever-agent/**/*',
            './node_modules/form-data/**/*',
            './node_modules/generate-function/**/*',
            './node_modules/generate-object-property/**/*',
            './node_modules/graceful-readlink/**/*',
            './node_modules/har-validator/**/*',
            './node_modules/has-ansi/**/*',
            './node_modules/hawk/**/*',
            './node_modules/hoek/**/*',
            './node_modules/http-signature/**/*',
            './node_modules/inherits/**/*',
            './node_modules/is-my-json-valid/**/*',
            './node_modules/is-property/**/*',
            './node_modules/is-typedarray/**/*',
            './node_modules/isarray/**/*',
            './node_modules/isstream/**/*',
            './node_modules/jodid25519/**/*',
            './node_modules/jsbn/**/*',
            './node_modules/json-schema/**/*',
            './node_modules/json-stringify-safe/**/*',
            './node_modules/jsonpointer/**/*',
            './node_modules/jsprim/**/*',
            './node_modules/lru-cache/**/*',
            './node_modules/mime-db/**/*',
            './node_modules/mime-types/**/*',
            './node_modules/node-uuid/**/*',
            './node_modules/oauth-sign/**/*',
            './node_modules/pinkie/**/*',
            './node_modules/pinkie-promise/**/*',
            './node_modules/process-nextick-args/**/*',
            './node_modules/qs/**/*',
            './node_modules/readable-stream/**/*',
            './node_modules/request/**/*',
            './node_modules/sntp/**/*',
            './node_modules/sshpk/**/*',
            './node_modules/string_decoder/**/*',
            './node_modules/stringstream/**/*',
            './node_modules/strip-ansi/**/*',
            './node_modules/supports-color/**/*',
            './node_modules/tough-cookie/**/*',
            './node_modules/tunnel-agent/**/*',
            './node_modules/tweetnacl/**/*',
            './node_modules/underscore/**/*',
            './node_modules/universal-analytics/**/*',
            './node_modules/util-deprecate/**/*',
            './node_modules/verror/**/*',
            './node_modules/xtend/**/*'
        ]
    };

// test if OS is windows
var isWin = /^win/.test(process.platform);

if ( isWin ) {
    config.options['winIco'] = '<%= settings.app %>/soundnode.ico';
}

module.exports = config;
