#!/bin/sh

# This script creates a *.deb file for the soundcloud app.
# It uses fpm @ https://github.com/jordansissel/fpm/
#
# Environment variables:
#     VERSION=X.X.X                   [mandatory]
#     DIST=(linux64 | linux32)        [default: linux64]
#
# Example: $ grunt build
#          $ VERSION=0.6.4 DIST=linux64 ./fpm/build-deb
#          or
#          $ VERSION=0.6.4 DIST=linux32 ./fpm/build-deb
#          $ ls *.deb

DIST=${DIST:-"linux64"}

if [ "$VERSION" = "" ]; then
    echo "Please set the VERSION environment variable."
    exit 3
fi

# We want to build 32 and 64 bit packages
if [ "$DIST" = "linux64" ]; then
    ARCH="amd64"
elif [ "$DIST" = "linux32" ]; then
    ARCH="i386"
else
    echo "Please set a valid DIST environment variable."
    echo "Choices are: DIST=linux64 or DIST=linux32"
    exit 4
fi

# Assert that the distribution files have been built
DIST_DIR="dist/Soundnode/$DIST"
if [ ! -d "$DIST_DIR" ]; then
    echo "Please run the build before trying to package. Hint:"
    echo "    grunt build"
    exit 5
fi

# Check if imagemagick is installed
convert -version >/dev/null 2>&1 || { echo "I require imagemagick but it's not installed. Aborting." >&2; exit 3; }

# Create package icon
convert -resize 48 app/soundnode.png fpm/soundnode-48x48.png

fpm -t deb \
    -s dir \
    --name "soundnode" \
    --architecture "$ARCH" \
    --license "GPL-3" \
    --maintainer "Jonas Gröger <jonas@huntun.de>" \
    --vendor "http://www.soundnodeapp.com/" \
    --url "http://www.soundnodeapp.com/" \
    --version "$VERSION" \
    --category "sound" \
    --iteration "1" \
    --package "fpm/packages" \
    --description "Soundnode App is an Open-Source project to support Soundcloud for desktop Mac, Windows, and Linux." \
    --after-install "fpm/create-symlink" \
    --after-remove "fpm/remove-symlink" \
    --deb-no-default-config-files \
    "$DIST_DIR/.=/usr/share/soundnode/" \
    "fpm/soundnode-48x48.png=/usr/share/icons/hicolor/48x48/apps/soundnode.png" \
    "fpm/soundnode.desktop=/usr/share/applications/"
