#!/bin/sh

# This script creates a *.deb file for the soundcloud app.
# It uses fpm @ https://github.com/jordansissel/fpm/
#
# Environment variables:
#     VERSION=X.X.X                   [mandatory]
#     DIST=(linux64 | linux32)        [default: linux64]
#
# Example: $ grunt build
#          $ VERSION=0.6.4 DIST=linux64 ./fpm/build-deb
#          or
#          $ VERSION=0.6.4 DIST=linux32 ./fpm/build-deb
#          $ ls *.deb

check_dependencies() {
    for PACKAGE_NAME in "$@"; do
        PACKAGE_STATUS="$(dpkg-query -W -f='${Status}' "$PACKAGE_NAME" 2>/dev/null | grep -q -P '^install ok installed$'; echo $?)"
        if [ "$PACKAGE_STATUS" -ne 0 ]; then
            printf " - I require %s to build soundnode. To solve this problem, run this: sudo apt install %s\n" "$1" "$1" >&2
            exit 1
        fi
    done
}

DIST=${DIST:-"linux64"}

if [ "$VERSION" = "" ]; then
    echo "Please set the VERSION environment variable."
    exit 3
fi

# We want to build 32 and 64 bit packages
if [ "$DIST" = "linux64" ]; then
    ARCH="amd64"
elif [ "$DIST" = "linux32" ]; then
    ARCH="i386"
else
    echo "Please set a valid DIST environment variable."
    echo "Choices are: DIST=linux64 or DIST=linux32"
    exit 4
fi

# Assert that the distribution files have been built
DIST_DIR="dist/Soundnode/$DIST"
if [ ! -d "$DIST_DIR" ]; then
    echo "Please run the build before trying to package. Hint:"
    echo "    grunt build"
    exit 5
fi

# Check build dependencies
check_dependencies python2.7 imagemagick libdbus-glib-1-dev wine

# Create package icon
convert -resize 48 app/soundnode.png fpm/soundnode-48x48.png

fpm -t deb \
    -s dir \
    --name "soundnode" \
    --architecture "$ARCH" \
    --license "GPL-3" \
    --maintainer "Jonas Gröger <jonas@huntun.de>" \
    --vendor "http://www.soundnodeapp.com/" \
    --url "http://www.soundnodeapp.com/" \
    --version "$VERSION" \
	--depends "libc6" \
	--depends "libnspr4" \
    --depends "libasound2" \
    --depends "libc6-i386" \
    --depends "libcairo2" \
    --depends "libdbus-1-3" \
    --depends "libexpat1" \
    --depends "libfontconfig1" \
    --depends "libfreetype6" \
    --depends "libgcc1" \
    --depends "libgconf-2-4" \
    --depends "libgdk-pixbuf2.0-0" \
    --depends "libglib2.0-0" \
    --depends "libgtk2.0-0" \
    --depends "libnotify4" \
    --depends "libnss3" \
    --depends "libpango-1.0-0" \
    --depends "libpangocairo-1.0-0" \
    --depends "libstdc++6" \
    --depends "libx11-6" \
    --depends "libxcomposite1" \
    --depends "libxcursor1" \
    --depends "libxdamage1" \
    --depends "libxext6" \
    --depends "libxfixes3" \
    --depends "libxi6" \
    --depends "libxrandr2" \
    --depends "libxrender1" \
    --depends "libxtst6" \
    --category "sound" \
    --iteration "1" \
    --package "fpm/packages" \
    --description "Soundnode App is an Open-Source project to support Soundcloud for desktop Mac, Windows, and Linux." \
    --after-install "fpm/create-symlink" \
    --after-remove "fpm/remove-symlink" \
    --deb-no-default-config-files \
    "$DIST_DIR/.=/usr/share/soundnode/" \
    "fpm/soundnode-48x48.png=/usr/share/icons/hicolor/48x48/apps/soundnode.png" \
    "fpm/soundnode.desktop=/usr/share/applications/"
